[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  node_bundler = "esbuild"
  external_node_modules = ["playwright-core", "playwright-aws-lambda"]

[functions."api"]
  timeout = 26
  memory = 2048

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
